version: 2.1

# List of all jobs.
jobs:
  # Build and test the project.
  build-and-test:
    docker:
      - image: circleci/golang:latest
    steps:
      # Update the project.
      - checkout

      # Install Rust.
      - run:
          name: Install Rust
          command: |
            test -d /usr/local/cargo || curl https://sh.rustup.rs -sSf | sh -s -- -y

      # Install `just` used to manage the project.
      - run:
          name: Install just
          command: |
            export PATH="$HOME/.cargo/bin:$PATH"
            test -f $HOME/.cargo/bin/just || cargo install just

      # Compile and install the Go library.
      - run:
          name: Compile and install the Go library
          command: |
            export PATH="$HOME/.cargo/bin:$PATH"
            just build

      # Run the library test suites.
      - run:
          name: Test the library
          command: |
            export PATH="$HOME/.cargo/bin:$PATH"
            just test

  # Build and test the project on macOS.
  build-and-test-macos:
    macos:
      xcode: "9.0"
    steps:
      # Update the project.
      - checkout

      # Install Rust.
      - run:
          name: Install Rust
          command: |
            test -d /usr/local/cargo || curl https://sh.rustup.rs -sSf | sh -s -- -y

      # Install `just` used to manage the project.
      - run:
          name: Install just
          command: |
            export PATH="$HOME/.cargo/bin:$PATH"
            test -f $HOME/.cargo/bin/just || cargo install just

      # Compile and install the Go library.
      - run:
          name: Compile and install the Go library
          command: |
            export PATH="$HOME/.cargo/bin:$PATH"
            just build

      # Run the library test suites.
      - run:
          name: Test the library
          command: |
            export PATH="$HOME/.cargo/bin:$PATH"
            just test


# List of workflows.
workflows:
  version: 2

  # The build workflow.
  build:
    jobs:
      # Run the `build-and-test` job for the `trying` and `staging` branches only, and all tags.
      - build-and-test:
          filters:
            branches:
              only:
                - trying
                - staging
            tags:
              only: /.*/
      # Run the `build-and-test-macos` job for the `trying` and `staging` branches only, and all tags.
      - build-and-test-macos:
          filters:
            branches:
              only:
                - trying
                - staging
            tags:
              only: /.*/
